openapi: "3.1.0"
info:
  title: "Google Sheet 腳本助手 API"
  version: "1.0.0"
  description: "查詢與編輯腳本排程（不需 token）"

servers:
  - url: "https://script.google.com/macros/s/AKfycbxc9cVBib1QsoADRce-PQvlFSWKZGl4goYVG6Ihvgzahxq0KHZPttFu59Rk4tk7V0O3tQ/exec"

paths:
  /:
    get:
      summary: "查詢腳本資料"
      operationId: "getScriptData"
      parameters:
        - name: "date"
          in: "query"
          required: false
          schema:
            type: string
            example: "2025-04-12"
        - name: "start"
          in: "query"
          required: false
          schema:
            type: string
            example: "2025-04-12"
        - name: "end"
          in: "query"
          required: false
          schema:
            type: string
            example: "2025-04-15"
        - name: "field"
          in: "query"
          required: false
          description: "用逗號分隔的欄位名稱，如：B腳本主題,B腳本收尾方式"
          schema:
            type: string
            example: "B腳本主題,B腳本收尾方式"
      responses:
        "200":
          description: "成功查詢資料"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
