openapi: "3.1.0"
info:
  title: "Google Sheet 腳本查詢 API"
  version: "1.1.0"
  description: "支援單日與範圍查詢，可指定欄位，來自 Google Apps Script 的 Web API"

servers:
  - url: "https://script.google.com/macros/s/AKfycbxc9cVBib1QsoADRce-PQvlFSWKZGl4goYVG6Ihvgzahxq0KHZPttFu59Rk4tk7V0O3tQ/exec"

paths:
  /:
    get:
      summary: "查詢腳本資料"
      operationId: getScriptData
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            example: "2025-04-12"
        - name: start
          in: query
          required: false
          schema:
            type: string
            example: "2025-04-12"
        - name: end
          in: query
          required: false
          schema:
            type: string
            example: "2025-04-15"
        - name: field
          in: query
          required: false
          schema:
            type: string
            example: "日期,B腳本主題,B腳本收尾方式"
      responses:
        "200":
          description: 成功回傳腳本資料
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
